      - name: Restore status cache
        uses: actions/cache@v4
        with:
          path: last_status.txt
          key: status-cache-${{ github.run_id }} # Тимчасовий ключ
          restore-keys: status-cache-

      - name: Run test
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python test.py

      - name: Save status cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: last_status.txt
          key: status-cache-${{ github.run_id }}
